server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    port: 6379
    host: 39.107.26.9
    password: 123456
  application:
    name: book-consumer


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-40.40logger{39} : %m%n"
  level:
    root: info
  file:
    path: log/springboot-demo.log

rocketmq:
  name-server: 39.107.26.9:9876
  producer:
    group: book-producer
    send-message-timeout: 6000
    retry-times-when-send-failed: 2


